{{- define "common.deployment" -}}

{{- $common := dict "Values" .Values.common -}} # Values з common Chart
{{- $noCommon := omit .Values "common" -}} # Values з основного Chart
{{- $overrides := dict "Values" $noCommon -}} # записуємо common Values в змінну Values
{{- $noValues := omit . "Values" -}} # містить усе крім Values, зокрема Chart, Release
{{- with merge $noValues $overrides $common -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          name: {{ .Values.image.name }}
          imagePullPolicy: Never
          {{- if .Values.service }}
          ports:
            {{- range .Values.service.ports }}
              - containerPort: {{ .containerPort }}
                name: {{ .name }}
            {{- end}}
          {{- end}}
          envFrom:
            - configMapRef:
                optional: true
                name: {{ include "common.fullname" $ }}-config
            - secretRef:
                optional: true
                name: {{ include "common.fullname" $ }}-secret
{{- end -}}
{{- end -}}