replicaCount: 1

selector:
  app: notify

image:
  name: notify
  tag: 0.1
  port: 8080

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

configs:
  KAFKA_HOST: "local-kafka:9092"
  CONSUMER_TOPIC: order-status-changed
  BREVO_API_KEY: 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
